poll_interval: 150  # ポーリング間隔（秒）

routers:
  - name: rtx-main
    host: 192.168.1.1
    community: public
    version: 2c
    port: 161
    timeout: 2
    retries: 1
    interfaces:
      - if_index: 1
        name: LAN1
      - if_index: 2
        name: LAN2

public_graphs:
   - router: rtx-main
     if_index: 2
